::
:: @file hyperv-backup.bat
:: @version v1.4
::
:: @url https://innovarew.appspot.com/
:: @author Innovarew <innovarew.solutions (at) gmail (dot) com>
:: @copyright (C) 2013 Innovarew Solutions. All Rights Reserved.
:: @license Proprietary and confidential
::     Unauthorized copying of this file, via any medium is strictly prohibited.
:: Contact us if you are interested in using our products and services.
::
:: Changelog:
::
:: [dd/mm/yyyy]        [author]
:: [brief description]
::
:: 21/01/2013        innovare.solutions
:: v1.0 Initial version
::

@echo off

:: Configurable options: edit hyperv-backup-config.bat
:: (do not edit this file, instead place settings in the config file)

:: Prevent double-click execution
if %0 == "%~0" (
    pause
)

:: Non-Configurable options
set cwd=%~dp0
set hypervbackup="hyperv-backup"
set hypervbackupexe=%cwd%\hyperv-backup.exe
set hypervbackupbat=%cwd%\hyperv-backup.bat
set hypervbackupconf=%cwd%\hyperv-backup-config.bat

if "%1%" == "usage" (
    :: show hyperv-backup.bat usage
    echo usage: %0 [usage daily disable status]
    echo - usage: show hyperv-backup.bat usage
    echo - daily: schedule daily hyperv-backup.bat task
    echo - disable: delete hyperv-backup.bat daily schedule task
    echo - status: show hyperv-backup.bat status
    echo - otherwise, run the hyperv-backup

    :: Show hyperv-backup usage & version info
    %hypervbackupexe%

) else if "%1%" == "daily" (
    :: set hyperv-backup.bat as schedule a daily task
    schtasks /Delete /TN %hypervbackup%
    schtasks /Create /SC DAILY /TN %hypervbackup% /TR %hypervbackupbat% /ST 00:00 /RU SYSTEM
) else if "%1%" == "disable" (
    :: delete hyperv-backup.bat daily schedule task
    schtasks /Delete /TN %hypervbackup%
) else if "%1%" == "status" (
    :: show hyperv-backup.bat status"
    schtasks /Query /TN %hypervbackup%
    schtasks /Query /TN %hypervbackup% /FO LIST /V
) else (
    :: otherwise, run the hyperv-backup
    cd %cwd%
    call %hypervbackupconf%
)

:: set exec files as readonly
attrib +r %hypervbackupexe%
attrib +r %hypervbackupbat%
attrib +r %hypervbackupconf%
